    @startuml
'https://plantuml.com/class-diagram

class Main

class StartMenu {
+ void startSession()
+ int knitOrCrochet()
+ int chooseLevel()
+ int amountOfYarn()
+ int chooseNeedleSize()
+ int chooseYarnType()
+ int chooseGauge()
+ ArrayList<Pattern> showPatterns()
+ boolean tryAgain()
+ Pattern getRandomPattern()
+ void endSession()
}

class Pattern {
- String name
- double needleSize
- int yarnAmount
- String level
- String yarnType
- String category
- int gauge
- ArrayList<Pattern> beginnerCrochet
- ArrayList<Pattern> intermediateCrochet
- ArrayList<Pattern> advancedCrochet
- ArrayList<Pattern> beginnerKnit
- ArrayList<Pattern> intermediateKnit
- ArrayList<Pattern> advancedKnit
+ String toString()
+ ArrayList<Pattern> showPatternsCrochetBeginner()
+ ArrayList<Pattern> showPatternsCrochetIntermediate()
+ ArrayList<Pattern> showPatternsCrochetAdvanced()
+ ArrayList<Pattern> showPatternsKnitBeginner()
+ ArrayList<Pattern> showPatternsKnitIntermediate()
+ ArrayList<Pattern> showPatternsKnitAdvanced()
+ ArrayList<Pattern> searchPatterns()
+ String getName()
+ double getNeedleSize()
+ int getYarnAmount()
+ String getLevel()
+ String getYarnType()
+ String getCategory()
+ int getGauge()
+ String ifExtraMaterials()
}

package test {
class Test {
+ boolean enoughYarnForPattern()
+ ArrayList<Recipe> getPatternsByDifficulty()
+ String testToStringOutput()
}
}

package util {
class TextUI {
+ String displayMsg()
+ String promptTxt()
+ int promptNumber()
+ boolean promptYesOrNo()
}
}

package db {
class DB {
+ getConnection()
}
}

package gui {
class YarnGUI {
+ createAndShowGUI()
}
}

Main *-- StartMenu
StartMenu -- User
User -- Pattern
StartMenu *-- Pattern
Pattern *-- Level
Pattern *-- NeedleSize
Pattern *-- YarnAmount
Pattern *-- YarnType
Pattern *-- ExtraMaterials
Pattern *-- Gauge
StartMenu *- TextUI

enum Level {
BEGINNER
INTERMEDIATE
ADVANCED
}

enum NeedleSize {
2.0 MM
2.5 MM
3.0 MM
3.5 MM
4.0 MM
5.0 MM
6.0 MM
7.0 MM
}

enum YarnAmount {
25 GRAM
50 GRAM
75 GRAM
100 GRAM
125 GRAM
150 GRAM
}

enum YarnType {
WOOL
COTTON
MOHAIR
}

enum ExtraMaterials {
EMBROIDERY THREAD
WADDING
}

enum Gauge {
20 STITCHES
23 STITCHES
26 STITCHES
}

@enduml